resources:
- name: deploy-photon
  type: git
  source:
    uri: https://github.com/skazi-pivotal/deploy-photon.git
    branch: master

- name: bosh-photon-cpi-release
  type: git
  source:
    uri: git@github.com:vmware/bosh-photon-cpi-release.git
    branch: master
    private_key: {{githubsshkey}}


- name: photon-run-id
  type: semver
  source:
    branch: version
    driver: git
    file: version
    initial_version: 1.0.0
    uri: git@github.com:skazi-pivotal/deploy-photon.git
    private_key: {{githubsshkey}}
    git_user: skazi@pivotal.io

jobs:

- name: p2-task1-Deploy-BOSH
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - get: photon-run-id
    trigger: true
  - get: deploy-photon
    trigger: false
  - get: bosh-photon-cpi-release
    trigger: false
  - task: p2-1-deploy-bosh
    config:
      platform: linux
      image: docker:///virtmerlin/deploy-worker
      inputs:
        - name: deploy-photon
        - name: bosh-photon-cpi-release
      run:
        path: deploy-photon/ci/tasks/deploy-bosh.sh
      params:
        ova_ip: {{ova_ip}}
        photon_release: {{photon_release}}
        bosh_manifest: {{bosh_manifest}}
        bosh_deployment_network_name: {{bosh_deployment_network}}
        bosh_deployment_network: {{bosh_deployment_network}}
        bosh_deployment_network_subnet: {{bosh_deployment_network_subnet}}
        bosh_deployment_network_gw: {{bosh_deployment_network_gw}}
        bosh_deployment_network_dns: {{bosh_deployment_network_dns}}
        bosh_deployment_network_ip: {{bosh_deployment_network_ip}}
        bosh_deployment_user: {{bosh_deployment_user}}
        bosh_deployment_passwd: {{bosh_deployment_passwd}}
        photon_user: {{photon_user}}
        photon_passwd: {{photon_passwd}}
        photon_ignore_cert: {{photon_ignore_cert}}
        photon_tenant: {{photon_tenant}}
        photon_project: {{photon_project}}
        cli_url: {{cli_url}}

- name: p2-task2-Upload-PCF
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - get: photon-run-id
    trigger: true
    passed: [p2-task1-Deploy-BOSH]
  - get: deploy-photon
    trigger: false
  - task: p2-2-upload-ERT
    config:
      platform: linux
      image: docker:///virtmerlin/deploy-worker
      inputs:
        - name: deploy-photon
      run:
        path: deploy-photon/ci/tasks/upload-pcf.sh
        args: [elastic-runtime,{{pcf_ert_version}}]
      params:
        ova_ip: {{ova_ip}}
        bosh_cpi: {{bosh_cpi}}
        bosh_manifest: {{bosh_manifest}}
        bosh_deployment_network_ip: {{bosh_deployment_network_ip}}
        bosh_deployment_user: {{bosh_deployment_user}}
        bosh_deployment_passwd: {{bosh_deployment_passwd}}
        pcf_ert_version: {{pcf_ert_version}}
        pcf_pivnet_token: {{pcf_pivnet_token}}

- name: p2-task3-Deploy-PCF
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - get: photon-run-id
    trigger: true
    passed: [p2-task2-Upload-PCF]
  - get: deploy-photon
    trigger: false
  - task: p2-3-1-deploy-ERT
    config:
      platform: linux
      image: docker:///virtmerlin/deploy-worker
      inputs:
        - name: deploy-photon
      run:
        path: deploy-photon/ci/tasks/deploy-pcf.sh
      params:
        ova_ip: {{ova_ip}}
        bosh_deployment_network: {{bosh_deployment_network}}
        bosh_deployment_network_ip: {{bosh_deployment_network_ip}}
        bosh_deployment_user: {{bosh_deployment_user}}
        bosh_deployment_passwd: {{bosh_deployment_passwd}}
        pcf_manifest: {{pcf_manifest}}
        cli_url: {{cli_url}}

  - task: p2-3-2-test-ERT
    config:
      platform: linux
      image: docker:///virtmerlin/deploy-worker
      inputs:
        - name: deploy-photon
      run:
        path: deploy-photon/ci/tasks/run-errands.sh
      params:
        bosh_deployment_network_ip: {{bosh_deployment_network_ip}}
        bosh_deployment_user: {{bosh_deployment_user}}
        bosh_deployment_passwd: {{bosh_deployment_passwd}}
